import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import { Header } from '@/components/header';
import { Footer } from '@/components/footer';

import 'normalize.css';
import './globals.scss';

import dayjs from 'dayjs';
import 'dayjs/locale/uk';

dayjs.locale('uk');

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Грумінг салон - Bastidot',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/favicon.ico' }],
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => {
  return (
    <html lang="ua">
      <body className={montserrat.variable}>
        <Header />
        {children}
        <div id="modal-root" />
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
