import { ReactNode } from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Montserrat } from 'next/font/google';

import {Header} from '@/components/header'

import 'normalize.css';
import './globals.scss';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => {
  return (
    <html lang="ua">
      <body className={montserrat.variable}>
        <Header />
        <nav>
          <ul>
            <li>
              <Link href="/form-example">Form Example</Link>
            </li>
          </ul>
        </nav>
        <div style={{ height: 100 }} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
