export const services = [
  {
    id: 1,
    serviceType: 'Повний комплекс',
    breedName: 'Мальтіпу',
    defaultPrice: 1000,
    vipPrice: 1500,
    durationHour: 3,
    durationMin: 30,
  },
  {
    id: 2,
    serviceType: 'Гігієнічний догляд',
    breedName: 'Мальтіпу',
    defaultPrice: 1000,
    vipPrice: 1500,
    durationHour: 3,
    durationMin: 30,
  },
  {
    id: 3,
    serviceType: 'Преміум комплекс',
    breedName: 'Мальтіпу',
    defaultPrice: 1000,
    vipPrice: 1500,
    durationHour: 3,
    durationMin: 30,
  },
  {
    id: 4,
    serviceType: 'Повний комплекс',
    breedName: 'Мальтіпу',
    defaultPrice: 1000,
    vipPrice: 1500,
    durationHour: 3,
    durationMin: 30,
  },
  {
    id: 5,
    serviceType: 'Гігієнічний догляд',
    breedName: 'Мальтіпу',
    defaultPrice: 1000,
    vipPrice: 1500,
    durationHour: 3,
    durationMin: 30,
  },
];
